### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by Zumbalamambo** [SolarFramework/SolARUnityPlugin#1]
Isn't it compatible with Android and iOS?

**Comment by granger35** [comment]
An Android version is in progress on the develop branch. It requires to configure the Android SDK and NDK for QT creator and will be included in the next release (i hope for end of July). Concerning iOS, it is in the roadmap but not the main priority. We prefer first to focus on new features for distributing SolAR pipelines into the cloud.

**Comment by Zumbalamambo** [comment]
@granger35 nice! Does the slam pipeline allow localization on a global map?

**Comment by granger35** [comment]
We are working on it. Have a look to the branch features/StorageComponents
