### ISSUE TITLE
[0.8.0] Missing scripts in SolARExpert prefab

### ISSUE THREAD

**Issue by npacqueriaud** [SolarFramework/SolARUnityPlugin#2]
Hello there,
I tried to use the new release for Windows [0.8.0], but I noticed that the gameobject _PipelineManager_ in the _SolARExpert_ prefab has missing scripts.
Is it due to the pre-release status and will be fixed in release?

**Comment by granger35** [comment]
Dear Nicolas,
The Unity plugin is not yet ready for the v0.8.0. Indeed, some SolAR interfaces have changed and includes multi-inheriting what is not fully compliant with SWIG scripts to generate C# wrapper for Unity. We are working hardly on it, and we hope to solve this issue soon. In the meantime, I recommend that you use the v0.7.0 unity plugin version.
Thank you.

**Comment by jim-bcom** [comment]
Assuming this is now obsolete.
