### ISSUE TITLE
[0.9.0] SLAM pipeline of the expert scene not working

### ISSUE THREAD

**Issue by ahaut** [SolarFramework/SolARUnityPlugin#3]
Hello 
I tried to use the SLAM pipeline of the expert scene, but I did not manage to make work. I got the error "Unknown UUID for: IPointCloudManager".
In the README, the documentation of the expert mod is written with strikethrough text, but the scene is still there.
Should it be working?

**Comment by jim-bcom** [comment]
Hello,

This scene is currently not supported, it should be absent from the latest version of the Unity package:
https://github.com/SolarFramework/SolARUnityPlugin/releases/tag/0.9.1

Sorry for the confusion.
